apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-redis-depl
spec:
  replicas: 1
  #selector is how deployment find a pod
  selector:
    matchLabels:
      app: expiration-redis
  template:
    metadata:
      labels:
        app: expiration-redis
    spec:
      containers:
        - name: expiration-redis
          # image staing in docker hub referes to image  what is create
          image: redis
---
apiVersion: v1
kind: Service
metadata:
  name: expiration-redis-srv
spec:
  #that selector telling service wjich pods itis goint to access to
  selector:
    app: expiration-redis
  ports:
    # that name we put for logging porposes
    - name: db
      protocol: TCP
      port: 6379
      targetPort: 6379
